# Generated by Django 6.0.4 on 2026-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseresult',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parseresult',
            name='h1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parseresult',
            name='is_success',
            field=models.BooleanField(default=True),
        ),
    ]
